# Generated by Django 3.2.8 on 2021-11-04 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20211103_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_category', models.CharField(max_length=100, null=True)),
                ('condition', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=100, null=True)),
                ('drug_image', models.ImageField(default='drug_default.jpg', upload_to='drugs/%Y/%m/%d/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Cardiovascular',
        ),
        migrations.DeleteModel(
            name='Gastrointestinal',
        ),
        migrations.DeleteModel(
            name='Respiratory',
        ),
    ]
