# Generated by Django 3.2.8 on 2021-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_auto_20211104_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='condition',
        ),
        migrations.AddField(
            model_name='drug',
            name='condition',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
