# Generated by Django 3.2.8 on 2021-11-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_auto_20211104_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='drug',
            name='generic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
