# Generated by Django 3.2.7 on 2021-10-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'verbose_name_plural': 'MedicalHistories'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecords',
            options={'verbose_name_plural': 'MedicalRecords'},
        ),
    ]
