# Generated by Django 3.2.7 on 2021-10-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20211009_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalhistory',
            name='current_medication',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='ever_had',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='other_illness',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='other_information',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='previous_operation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
