# Generated by Django 3.2.7 on 2021-10-15 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0020_alter_doctor_profile_image'),
        ('documents', '0003_auto_20211015_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor'),
        ),
    ]
