# Generated by Django 3.2.7 on 2021-10-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_medicalhistory_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='blood_group',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
