# Generated by Django 3.2.8 on 2021-10-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.BooleanField(default=False),
        ),
    ]
