# Generated by Django 3.2.8 on 2021-10-16 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_appointment_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
