# Generated by Django 3.2.8 on 2021-10-20 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_medicalhistory_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalhistory',
            name='height',
        ),
    ]
