# Generated by Django 3.2.8 on 2021-11-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_remove_medicalhistory_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='prescription_file',
        ),
        migrations.AddField(
            model_name='prescription',
            name='days',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quaintity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='time',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
