# Generated by Django 3.2.8 on 2021-11-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_rename_quaintity_prescription_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='time',
        ),
        migrations.AddField(
            model_name='prescription',
            name='afternoon',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='evening',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='morning',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='night',
            field=models.TextField(max_length=10, null=True),
        ),
    ]
