# Generated by Django 3.2.8 on 2021-11-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_auto_20211108_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='afternoon',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='evening',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='morning',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='night',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
