# Generated by Django 3.2.8 on 2021-11-12 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20211108_2225'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
