# Generated by Django 3.2.8 on 2021-11-12 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_patientappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientAppointment',
        ),
    ]
