# Generated by Django 3.2.8 on 2021-10-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(default='default.png', upload_to='patients/%Y/%m/%d/'),
        ),
    ]
