# Generated by Django 3.2.7 on 2021-10-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0009_alter_doctor_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='doctors/%Y/%m/%d/'),
        ),
    ]
