# Generated by Django 3.2.7 on 2021-10-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0010_alter_doctor_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorspecialization',
            name='services',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
