# Generated by Django 3.2.7 on 2021-10-09 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0014_alter_qualification_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialization',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='doctors.doctor'),
        ),
    ]
