# Generated by Django 3.2.7 on 2021-10-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0015_alter_doctorspecialization_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialization',
            name='specialized_category',
            field=models.CharField(default='Update Profile', max_length=50),
        ),
    ]
