# Generated by Django 3.2.7 on 2021-10-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0018_auto_20211010_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorspecialization',
            name='specialized_category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
