# Generated by Django 3.2.8 on 2021-10-16 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0021_alter_doctor_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorspecialization',
            name='services',
        ),
    ]
