# Generated by Django 3.2.8 on 2021-11-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0023_appointmenttime'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='from_to',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
