# Generated by Django 3.2.8 on 2021-11-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0025_patientappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='appointment_date',
            field=models.DateField(null=True),
        ),
    ]
