# Generated by Django 3.2.8 on 2021-11-12 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0027_alter_patientappointment_appoint_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='appoint_day',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
