# Generated by Django 3.2.8 on 2021-11-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0028_appointmenttime_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmenttime',
            name='patient',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
