# Generated by Django 3.2.8 on 2021-11-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0028_alter_patientappointment_appoint_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointmenttime',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
