# Generated by Django 3.2.8 on 2021-11-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0030_auto_20211119_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmenttime',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointmenttime',
            name='month',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
